### ISSUE TITLE
Link Generation for Subfolder does not work

### ISSUE THREAD

**Issue by sandraInterad** [andref15/G4mvc#17]
I have following configuration in my application's g4mvc.json configuration file:

{
  "UseVirtualPathProcessor": true,
  "EnableSubfoldersInViews":  true
}

Nevertheless Links for my Views within subfolders are not created.

My folder structure:
- Shared (Folder)
    - _Layout.cshtml
    - Grid (Folder)
        -  _Grid.cshtml

The link for _Layout.cshtml is sucessfully created but not for _Grid.cshtml

**Comment by andref15** [comment]
The issue seems to be that no property is generated for the sub folder classes
